"""
routers/client.py — Client-facing API endpoints.

All routes require role='client'.
Clients can only access their own data — enforced by using current_user["sub"]
as the client_id in every query (never trusting a client-supplied ID).
"""
from decimal import Decimal
from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, Request, UploadFile, status
from pydantic import BaseModel, Field
from typing import Optional

from auth.dependencies import require_role
from database import get_supabase
from services.transaction_service import (
    get_client_balance,
    submit_pay_in,
    submit_pay_out,
)
from services.bank_account_service import get_eligible_accounts_for_client
from services.storage_service import upload_proof

from datetime import datetime, timezone
from fastapi.responses import Response
from services.report_service import fetch_approved_transactions, generate_pdf, _parse_range

router = APIRouter(prefix="/api/client", tags=["client"])
ClientUser = Depends(require_role(["client"]))


class PayOutRequest(BaseModel):
    amount: float = Field(..., gt=0, description="Amount to withdraw in INR")


# ─── Dashboard ────────────────────────────────────────────────────────────────

@router.get("/dashboard")
async def client_dashboard(current_user: dict = ClientUser):
    """
    Returns the client's full balance breakdown and recent transactions.

    Fields:
        total_balance     — all approved pay_ins minus all approved pay_outs
        withdrawable_now  — matured pay_ins minus pay_outs (approved + pending)
        on_hold_amount    — total_balance - withdrawable_now (funds in 24h hold)
        next_unlock_at    — ISO timestamp when the next batch of funds unlocks
        deposit_headroom  — how much more the client can deposit before hitting account_limit
        has_stale_pending — True if any Pay-In has been pending > 12 hours
    """
    client_id = current_user["sub"]
    db = get_supabase()

    balance = await get_client_balance(client_id)

    # Deposit headroom and fee
    user = db.table("users").select("account_limit, fee_percentage").eq("id", client_id).maybe_single().execute()
    account_limit = user.data.get("account_limit") if user.data else None
    fee_percentage = user.data.get("fee_percentage") if user.data else 0.0
    deposit_headroom = None
    if account_limit is not None:
        deposit_headroom = max(0.0, float(account_limit) - balance["total_balance"])

    # Recent transactions (last 20)
    recent_txns = db.table("transactions").select(
        "id, type, gross_amount, fee_percentage, fee_amount, net_amount, status, created_at, matures_at, admin_notes"
    ).eq("client_id", client_id).order("created_at", desc=True).limit(20).execute()

    txns = recent_txns.data or []
    for t in txns:
        if t["status"] == "employee_approved":
            t["status"] = "pending"

    return {
        **balance,
        "account_limit": float(account_limit) if account_limit is not None else None,
        "deposit_headroom": deposit_headroom,
        "fee_percentage": float(fee_percentage),
        "recent_transactions": txns,
    }


# ─── Available Bank Accounts ──────────────────────────────────────────────────

@router.get("/bank-accounts")
async def get_available_bank_accounts(current_user: dict = ClientUser):
    """
    Returns only bank accounts that are:
    - is_active = True
    - remaining_capacity > 0 (or unlimited)
    Each includes label, upi_id, account_number, ifsc, remaining_capacity.
    """
    accounts = await get_eligible_accounts_for_client()
    # Only expose fields the client needs (not internal limit/usage data)
    return [
        {
            "id": a["id"],
            "label": a["label"],
            "upi_id": a.get("upi_id"),
            "account_number": a.get("account_number"),
            "ifsc": a.get("ifsc"),
            "remaining_capacity": a.get("remaining_capacity"),
        }
        for a in accounts
    ]


# ─── Pay-In ───────────────────────────────────────────────────────────────────

@router.post("/pay-in", status_code=status.HTTP_201_CREATED)
async def submit_pay_in_request(
    request: Request,
    amount: float = Form(..., gt=0),
    bank_account_id: str = Form(...),
    idempotency_key: str = Form(..., min_length=36, max_length=36),  # UUID v4
    proof_image: UploadFile = File(...),
    current_user: dict = ClientUser,
):
    """
    Submit a Pay-In (deposit) request.

    - amount: gross deposit amount in INR
    - bank_account_id: ID of the selected company bank account
    - idempotency_key: UUID v4 generated by client to prevent duplicate submissions
    - proof_image: JPEG/PNG/WebP payment screenshot (max 5 MB)

    Fee is calculated server-side from the client's stored fee_percentage.
    Balance is NOT updated until an Admin/Employee approves the transaction.
    """
    client_id = current_user["sub"]

    # Upload and validate the proof image
    proof_path = await upload_proof(proof_image, client_id)

    return await submit_pay_in(
        client_id=client_id,
        gross_amount=Decimal(str(amount)),
        bank_account_id=bank_account_id,
        proof_path=proof_path,
        idempotency_key=idempotency_key,
        ip_address=request.client.host if request.client else None,
    )


# ─── Pay-Out ──────────────────────────────────────────────────────────────────

@router.post("/pay-out", status_code=status.HTTP_201_CREATED)
async def submit_pay_out_request(
    body: PayOutRequest,
    request: Request,
    current_user: dict = ClientUser,
):
    """
    Submit a Pay-Out (withdrawal) request.

    - amount must not exceed withdrawable_now (matured funds minus pending requests)
    - No fee on Pay-Out — client receives exactly the requested amount
    - Validated server-side; disabled button in UI is not a security control
    """
    return await submit_pay_out(
        client_id=current_user["sub"],
        requested_amount=Decimal(str(body.amount)),
        ip_address=request.client.host if request.client else None,
    )


# ─── Transaction History ──────────────────────────────────────────────────────

@router.get("/transactions")
async def get_transaction_history(
    transaction_status: Optional[str] = Query(None, alias="status"),
    txn_type: Optional[str] = Query(None, alias="type"),
    page: int = Query(1, ge=1),
    per_page: int = Query(20, ge=1, le=100),
    current_user: dict = ClientUser,
):
    """Client's own transaction history — cannot access other clients' transactions."""
    db = get_supabase()
    query = db.table("transactions").select(
        "id, type, gross_amount, fee_percentage, fee_amount, net_amount, status, "
        "created_at, matures_at, admin_notes, bank_account_id",
        count="exact"
    ).eq("client_id", current_user["sub"])   # Always scoped to current client

    if transaction_status == "pending":
        query = query.in_("status", ["pending", "employee_approved"])
    elif transaction_status:
        query = query.eq("status", transaction_status)
    if txn_type:
        query = query.eq("type", txn_type)

    offset = (page - 1) * per_page
    result = query.order("created_at", desc=True).range(offset, offset + per_page - 1).execute()

    txns = result.data or []
    for t in txns:
        if t["status"] == "employee_approved":
            t["status"] = "pending"

    return {
        "transactions": txns,
        "total": result.count or 0,
        "page": page,
        "per_page": per_page,
    }

# ==========================================
# Export Report
# ==========================================

@router.get("/export")
async def export_client_report(
    range: str = Query("30d"),
    current_user: dict = ClientUser,
):
    start, end = _parse_range(range)
    client_id = current_user["sub"]
    transactions = fetch_approved_transactions(start, end, client_id=client_id)
    db = get_supabase()
    actor = db.table("users").select("display_name").eq("id", client_id).maybe_single().execute()
    generated_by = actor.data["display_name"] if actor.data else "Client"

    pdf_bytes = generate_pdf(transactions, start, end, generated_by, show_fees=False)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="my-transactions-{range}.pdf"'},
    )
