"""
services/report_service.py — Server-side PDF and Excel report generation.

PDF:  ReportLab (cross-platform, no system dependencies required on Windows)
Excel: openpyxl

All reports are generated from the authoritative database and include:
- Generation timestamp
- Generated-by user name
- Date range applied
- Point-in-time snapshot disclaimer
"""
import io
from datetime import datetime, timezone, timedelta
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from database import get_supabase


# ─── Data Fetching ────────────────────────────────────────────────────────────

def _parse_range(range_param: str) -> tuple[datetime, datetime]:
    """Parse a range string into (start, end) UTC datetimes."""
    now = datetime.now(timezone.utc)
    if range_param == "7d":
        return now - timedelta(days=7), now
    elif range_param == "30d":
        return now - timedelta(days=30), now
    else:
        return now - timedelta(days=30), now


def fetch_approved_transactions(
    start: datetime,
    end: datetime,
    client_id: str | None = None,
) -> list[dict]:
    """Fetch approved transactions for a date range, optionally filtered by client."""
    db = get_supabase()
    query = db.table("transactions").select(
        "*, client:users!client_id(display_name, client_code), "
        "processor:users!processed_by(display_name)"
    ).eq("status", "approved").gte("created_at", start.isoformat()).lte(
        "created_at", end.isoformat()
    ).order("created_at", desc=False)

    if client_id:
        query = query.eq("client_id", client_id)

    result = query.execute()
    return result.data or []


# ─── Shared Row Preparation ───────────────────────────────────────────────────

def _prepare_rows(transactions: list[dict]) -> tuple[list[dict], dict]:
    rows = []
    total_pay_in_gross = 0.0
    total_fees = 0.0
    total_pay_out = 0.0

    for t in transactions:
        client_info = t.get("client") or {}
        processed_info = t.get("processor") or {}

        gross = float(t.get("gross_amount", 0))
        fee = float(t.get("fee_amount", 0))
        net = float(t.get("net_amount", 0))

        row = {
            **t,
            "client_name": client_info.get("display_name", "—"),
            "client_code": client_info.get("client_code", "—"),
            "approved_by": processed_info.get("display_name", "—"),
            "gross_amount": gross,
            "fee_amount": fee,
            "net_amount": net,
        }
        rows.append(row)

        if t["type"] == "pay_in":
            total_pay_in_gross += gross
            total_fees += fee
        else:
            total_pay_out += gross

    totals = {
        "total_pay_in_gross": total_pay_in_gross,
        "total_fees": total_fees,
        "total_pay_out": total_pay_out,
    }
    return rows, totals


# ─── PDF Generation (ReportLab — Windows compatible) ─────────────────────────

def generate_pdf(
    transactions: list[dict],
    start: datetime,
    end: datetime,
    generated_by: str,
    show_fees: bool = True,
) -> bytes:
    """Render a styled PDF report using ReportLab (no GTK/system libs needed)."""
    rows, totals = _prepare_rows(transactions)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=20*mm, bottomMargin=20*mm,
        leftMargin=15*mm, rightMargin=15*mm,
    )
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        'CmsTitle', parent=styles['Heading1'],
        alignment=TA_CENTER, fontSize=16, spaceAfter=4
    )
    story.append(Paragraph("Raja CMS - Transaction Report", title_style))
    story.append(Spacer(1, 4*mm))

    # Meta info
    meta_style = ParagraphStyle(
        'Meta', parent=styles['Normal'],
        fontSize=8, textColor=colors.HexColor('#475569'), spaceAfter=6
    )
    story.append(Paragraph(
        f"Period: <b>{start.strftime('%d %b %Y')}</b> to <b>{end.strftime('%d %b %Y')}</b>"
        f"    Generated by: <b>{generated_by}</b>"
        f"    Generated at: <b>{datetime.now(timezone.utc).strftime('%d %b %Y %H:%M UTC')}</b>",
        meta_style
    ))
    story.append(Spacer(1, 4*mm))

    if show_fees:
        header = ["#", "Date", "Client", "Code", "Type", "Gross", "Fee%", "Fee", "Net", "Approved By"]
        data = [header]
        for i, t in enumerate(rows, 1):
            data.append([
                str(i),
                str(t.get("created_at", ""))[:10],
                str(t.get("client_name", "")),
                str(t.get("client_code", "")),
                str(t.get("type", "")).replace("_", "-").upper(),
                f"{t.get('gross_amount', 0):,.2f}",
                f"{t.get('fee_percentage', 0):.2f}%",
                f"{t.get('fee_amount', 0):,.2f}",
                f"{t.get('net_amount', 0):,.2f}",
                str(t.get("approved_by", "")),
            ])
        # Totals rows
        data.append([""] * 10)  # blank separator
        data.append(["", "", "", "", "Total Pay-In (Gross)",
                     f"{totals['total_pay_in_gross']:,.2f}", "", f"{totals['total_fees']:,.2f}",
                     f"{totals['total_pay_in_gross'] - totals['total_pay_out']:,.2f}", ""])
    else:
        header = ["#", "Date", "Client", "Code", "Type", "Amount", "Approved By"]
        data = [header]
        for i, t in enumerate(rows, 1):
            data.append([
                str(i),
                str(t.get("created_at", ""))[:10],
                str(t.get("client_name", "")),
                str(t.get("client_code", "")),
                str(t.get("type", "")).replace("_", "-").upper(),
                f"{t.get('gross_amount', 0):,.2f}",
                str(t.get("approved_by", "")),
            ])
        # Totals rows
        data.append([""] * 7)  # blank separator
        data.append(["", "", "", "", "Total Pay-In", f"{totals['total_pay_in_gross']:,.2f}", ""])
        data.append(["", "", "", "", "Total Pay-Out", f"{totals['total_pay_out']:,.2f}", ""])

    align_col_start = 5
    align_col_end = 8 if show_fees else 5

    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND',   (0, 0),  (-1, 0),  colors.HexColor('#0f172a')),
        ('TEXTCOLOR',    (0, 0),  (-1, 0),  colors.white),
        ('FONTNAME',     (0, 0),  (-1, 0),  'Helvetica-Bold'),
        ('FONTSIZE',     (0, 0),  (-1, -1), 7),
        ('ROWBACKGROUNDS', (0, 1), (-1, -3), [colors.white, colors.HexColor('#f8fafc')]),
        ('GRID',         (0, 0),  (-1, -3), 0.4, colors.HexColor('#e2e8f0')),
        ('ALIGN',        (align_col_start, 0),  (align_col_end, -1),  'RIGHT'),
        ('TOPPADDING',   (0, 0),  (-1, -1), 3),
        ('BOTTOMPADDING',(0, 0),  (-1, -1), 3),
        ('FONTNAME',     (0, -1), (-1, -1), 'Helvetica-Bold'),
    ]))
    story.append(table)
    story.append(Spacer(1, 6*mm))

    # Footer
    footer_style = ParagraphStyle(
        'Footer', parent=styles['Normal'],
        fontSize=7, textColor=colors.HexColor('#94a3b8'), alignment=TA_CENTER
    )
    story.append(Paragraph(
        "Point-in-time snapshot. Data reflects the state of the database at the time of generation.",
        footer_style
    ))

    doc.build(story)
    return buffer.getvalue()


# ─── Excel Generation ─────────────────────────────────────────────────────────

def generate_excel(
    transactions: list[dict],
    start: datetime,
    end: datetime,
    generated_by: str,
    show_fees: bool = True,
) -> bytes:
    """Generate .xlsx report using openpyxl."""
    rows, totals = _prepare_rows(transactions)
    wb = Workbook()
    ws = wb.active
    ws.title = "Transactions"

    # Styles
    header_fill = PatternFill("solid", fgColor="0F172A")
    header_font = Font(color="F8FAFC", bold=True, size=10)
    thin_border = Border(
        bottom=Side(style="thin", color="E2E8F0"),
    )

    if show_fees:
        # Title row
        ws.merge_cells("A1:J1")
        ws["A1"] = "Raja CMS — Transaction Report"
        ws["A1"].font = Font(bold=True, size=13, color="0F172A")
        ws["A1"].alignment = Alignment(horizontal="center")

        # Meta rows
        ws["A2"] = f"Period: {start.strftime('%d %b %Y')} to {end.strftime('%d %b %Y')}"
        ws["F2"] = f"Generated by: {generated_by}"
        ws["A3"] = f"Generated at: {datetime.now(timezone.utc).strftime('%d %b %Y %H:%M UTC')}"

        # Headers
        headers = ["#", "Date", "Client", "Code", "Type", "Gross (INR)", "Fee %", "Fee (INR)", "Net (INR)", "Approved By"]
        for col, h in enumerate(headers, 1):
            cell = ws.cell(row=5, column=col, value=h)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center")

        # Data rows
        for i, t in enumerate(rows, 1):
            row_num = 5 + i
            ws.cell(row=row_num, column=1, value=i)
            ws.cell(row=row_num, column=2, value=t.get("created_at", "")[:10])
            ws.cell(row=row_num, column=3, value=t.get("client_name"))
            ws.cell(row=row_num, column=4, value=t.get("client_code"))
            ws.cell(row=row_num, column=5, value=t.get("type", "").replace("_", "-").upper())
            ws.cell(row=row_num, column=6, value=t.get("gross_amount")).number_format = "#,##0.00"
            ws.cell(row=row_num, column=7, value=t.get("fee_percentage")).number_format = "0.00%"
            ws.cell(row=row_num, column=8, value=t.get("fee_amount")).number_format = "#,##0.00"
            ws.cell(row=row_num, column=9, value=t.get("net_amount")).number_format = "#,##0.00"
            ws.cell(row=row_num, column=10, value=t.get("approved_by"))
            for col in range(1, 11):
                ws.cell(row=row_num, column=col).border = thin_border

        # Totals
        last_row = 5 + len(rows) + 2
        ws.cell(row=last_row, column=8, value="Total Pay-In (Gross)").font = Font(bold=True)
        ws.cell(row=last_row, column=9, value=totals["total_pay_in_gross"]).number_format = "#,##0.00"
        ws.cell(row=last_row + 1, column=8, value="Total Fees").font = Font(bold=True)
        ws.cell(row=last_row + 1, column=9, value=totals["total_fees"]).number_format = "#,##0.00"
        ws.cell(row=last_row + 2, column=8, value="Total Pay-Out").font = Font(bold=True)
        ws.cell(row=last_row + 2, column=9, value=totals["total_pay_out"]).number_format = "#,##0.00"

        col_widths = [4, 12, 25, 10, 10, 14, 8, 14, 14, 20]
        for i, w in enumerate(col_widths, 1):
            ws.column_dimensions[get_column_letter(i)].width = w
    else:
        # Title row
        ws.merge_cells("A1:G1")
        ws["A1"] = "Raja CMS — Transaction Report"
        ws["A1"].font = Font(bold=True, size=13, color="0F172A")
        ws["A1"].alignment = Alignment(horizontal="center")

        # Meta rows
        ws["A2"] = f"Period: {start.strftime('%d %b %Y')} to {end.strftime('%d %b %Y')}"
        ws["E2"] = f"Generated by: {generated_by}"
        ws["A3"] = f"Generated at: {datetime.now(timezone.utc).strftime('%d %b %Y %H:%M UTC')}"

        # Headers
        headers = ["#", "Date", "Client", "Code", "Type", "Amount (INR)", "Approved By"]
        for col, h in enumerate(headers, 1):
            cell = ws.cell(row=5, column=col, value=h)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center")

        # Data rows
        for i, t in enumerate(rows, 1):
            row_num = 5 + i
            ws.cell(row=row_num, column=1, value=i)
            ws.cell(row=row_num, column=2, value=t.get("created_at", "")[:10])
            ws.cell(row=row_num, column=3, value=t.get("client_name"))
            ws.cell(row=row_num, column=4, value=t.get("client_code"))
            ws.cell(row=row_num, column=5, value=t.get("type", "").replace("_", "-").upper())
            ws.cell(row=row_num, column=6, value=t.get("gross_amount")).number_format = "#,##0.00"
            ws.cell(row=row_num, column=7, value=t.get("approved_by"))
            for col in range(1, 8):
                ws.cell(row=row_num, column=col).border = thin_border

        # Totals
        last_row = 5 + len(rows) + 2
        ws.cell(row=last_row, column=5, value="Total Pay-In").font = Font(bold=True)
        ws.cell(row=last_row, column=6, value=totals["total_pay_in_gross"]).number_format = "#,##0.00"
        ws.cell(row=last_row + 1, column=5, value="Total Pay-Out").font = Font(bold=True)
        ws.cell(row=last_row + 1, column=6, value=totals["total_pay_out"]).number_format = "#,##0.00"

        col_widths = [4, 12, 25, 10, 10, 16, 20]
        for i, w in enumerate(col_widths, 1):
            ws.column_dimensions[get_column_letter(i)].width = w

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()
